# Generated by Django 4.2.22 on 2025-06-22 08:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_alter_article_slug_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='primary_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, null=True, verbose_name='Primary Image'),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, null=True, verbose_name='Avatar'),
        ),
    ]
