# Generated by Django 4.2.22 on 2025-07-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_contactmessage_moderatorapplication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='primary_image_fit',
            field=models.CharField(choices=[('cover', 'Cover'), ('contain', 'Contain'), ('fill', 'Fill'), ('none', 'None'), ('scale-down', 'Scale Down')], default='cover', help_text='How should the primary image fit inside its container?', max_length=20),
        ),
    ]
