# Generated by Django 4.2.22 on 2025-07-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_article_primary_image_fit'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_fit',
            field=models.CharField(choices=[('cover', 'Cover'), ('contain', 'Contain'), ('fill', 'Fill'), ('none', 'None'), ('scale-down', 'Scale Down')], default='cover', help_text='Control how your avatar fits in the frame.', max_length=20),
        ),
    ]
